#!/bin/bash

if [[ $# -ne 3 ]]; then
    echo "Usage: ${0##*/} <config_file> <proto_dir> <output_dir>"
    exit 1
fi

config_file="$1"
proto_dir="$2"
output_dir="$3"

protoc -I$proto_dir --protoboiler_out=config=$config_file,my_opt=hello:$output_dir $proto_dir/*.proto
