
// DO NOT EDIT.
//
// Generated by the protoboiler plugin for the protocol buffer compiler.
// Source: stub.cpp.py

#include <cstdint>
#include <string>

template <class T>
class Repeated {
};

template <class T>
class StreamWriter {
};

template <class T>
class StreamReader {
};

namespace package1 {
    // Leading comment.
    enum class Enum1 {
        VALUE_1 = 0, // Trailing comment.
    };

    struct Message1 {
        struct NestedMessage1 {
            int32_t field_1;
        };

        int32_t field_1;
        ::package1::Message1::NestedMessage1 field_2;
        ::package1::Enum1 proto3_optional_field_3;
    };

    struct Message2 {
        Repeated<int32_t>* field_1;
        std::string field_2;
    };

    class Service1 {
        void Method1(StreamReader<::package1::Message2>* input, ::package1::Message1* output);
    };

} // package1

namespace routeguide {
    // Unit of distance.
    enum class DistanceUnit {
        METERS = 0,
        FEET = 1,
        KILOMETERS = 2,
        MILES = 3,
        NAUTICALMILES = 4,
        YARDS = 5,
    };

    // Points are represented as latitude-longitude pairs in the E7 representation
    // (degrees multiplied by 10**7 and rounded to the nearest integer).
    // Latitudes should be in the range +/- 90 degrees and longitude should be in
    // the range +/- 180 degrees (inclusive).
    struct Point {
        int32_t latitude;
        int32_t longitude;
    };

    // A latitude-longitude rectangle, represented as two diagonally opposite
    // points "lo" and "hi".
    struct Rectangle {
        // One corner of the rectangle.
        ::routeguide::Point lo;
        // The other corner of the rectangle.
        ::routeguide::Point hi;
    };

    // A feature names something at a given point.
    //
    // If a feature could not be named, the name is empty.
    struct Feature {
        enum class FeatureType {
            OTHER = 0, // Unknown feature.
            HOME = 1,
            WORK = 2,
            SHOP = 3,
            GAS = 4,
        };

        // The name of the feature.
        std::string name;
        // The point where the feature is detected.
        ::routeguide::Point location;
        // The type of the feature.
        Repeated<::routeguide::Feature::FeatureType>* type;
    };

    // A RouteNote is a message sent while at a given point.
    struct RouteNote {
        // The location from which the message is sent.
        ::routeguide::Point location;
        // The message to be sent.
        std::string message;
    };

    // A RouteSummary is received in response to a RecordRoute RPC.
    //
    // It contains the number of individual points received, the number of
    // detected features, and the total distance covered as the cumulative sum of
    // the distance between each point.
    struct RouteSummary {
        struct Time {
            int32_t sec; // Time in seconds.
        };

        // The number of points received.
        int32_t point_count;
        // The number of known features passed while traversing the route.
        int32_t feature_count;
        // The covered distance in DistanceUnit.
        int32_t distance;
        // The duration of the traversal.
        ::routeguide::RouteSummary::Time elapsed_time;
        // The distance unit.
        ::routeguide::DistanceUnit distance_unit;
    };

    // Interface exported by the server.
    class RouteGuide {
        void GetFeature(const ::routeguide::Point* input, ::routeguide::Feature* output);
        void ListFeatures(const ::routeguide::Rectangle* input, StreamWriter<::routeguide::Feature>* output);
        void RecordRoute(StreamReader<::routeguide::Point>* input, ::routeguide::RouteSummary* output);
        void RouteChat(StreamReader<::routeguide::RouteNote>* input, StreamWriter<::routeguide::RouteNote>* output);
    };

} // routeguide
