
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protoboiler plugin for the protocol buffer compiler.
// Source: stub.swift.py

//
// package1
//

// Leading comment.
public enum Package1_Enum1: Int {
    case value1 = 0 // Trailing comment.
}

public struct Package1_Message1 {
    public struct NestedMessage1 {
        var field_1: Int32
    }

    var field_1: Int32
    var field_2: Package1_Message1.NestedMessage1
    var proto3_optional_field_3: Package1_Enum1?
}

public struct Package1_Message2 {
    var field_1: [Int32]
    var field_2: String
}

protocol Package1_Service1 {
    func Method1(request: AsyncThrowingStream<Package1_Message2, Error>) async throws -> Package1_Message1
}

//
// routeguide
//

// Unit of distance.
public enum Routeguide_DistanceUnit: Int {
    case meters = 0
    case feet = 1
    case kilometers = 2
    case miles = 3
    case nauticalmiles = 4
    case yards = 5
}

// Points are represented as latitude-longitude pairs in the E7 representation
// (degrees multiplied by 10**7 and rounded to the nearest integer).
// Latitudes should be in the range +/- 90 degrees and longitude should be in
// the range +/- 180 degrees (inclusive).
public struct Routeguide_Point {
    var latitude: Int32
    var longitude: Int32
}

// A latitude-longitude rectangle, represented as two diagonally opposite
// points "lo" and "hi".
public struct Routeguide_Rectangle {
    // One corner of the rectangle.
    var lo: Routeguide_Point
    // The other corner of the rectangle.
    var hi: Routeguide_Point
}

// A feature names something at a given point.
//
// If a feature could not be named, the name is empty.
public struct Routeguide_Feature {
    public enum FeatureType: Int {
        case other = 0 // Unknown feature.
        case home = 1
        case work = 2
        case shop = 3
        case gas = 4
    }

    // The name of the feature.
    var name: String
    // The point where the feature is detected.
    var location: Routeguide_Point
    // The type of the feature.
    var type: [Routeguide_Feature.FeatureType]
}

// A RouteNote is a message sent while at a given point.
public struct Routeguide_RouteNote {
    // The location from which the message is sent.
    var location: Routeguide_Point
    // The message to be sent.
    var message: String
}

// A RouteSummary is received in response to a RecordRoute RPC.
//
// It contains the number of individual points received, the number of
// detected features, and the total distance covered as the cumulative sum of
// the distance between each point.
public struct Routeguide_RouteSummary {
    public struct Time {
        var sec: Int32 // Time in seconds.
    }

    // The number of points received.
    var point_count: Int32
    // The number of known features passed while traversing the route.
    var feature_count: Int32
    // The covered distance in DistanceUnit.
    var distance: Int32
    // The duration of the traversal.
    var elapsed_time: Routeguide_RouteSummary.Time
    // The distance unit.
    var distance_unit: Routeguide_DistanceUnit?
}

// Interface exported by the server.
protocol Routeguide_RouteGuide {
    func GetFeature(request: Routeguide_Point) async throws -> Routeguide_Feature
    func ListFeatures(request: Routeguide_Rectangle) -> AsyncThrowingStream<Routeguide_Feature, Error>
    func RecordRoute(request: AsyncThrowingStream<Routeguide_Point, Error>) async throws -> Routeguide_RouteSummary
    func RouteChat(request: AsyncThrowingStream<Routeguide_RouteNote, Error>) -> AsyncThrowingStream<Routeguide_RouteNote, Error>
}
